### ISSUE TITLE
Pocket list bulk import

### ISSUE THREAD

**Issue by rezgi** [nybbles/obsidian-pocket#44] opened 2021-08-27 09:50 UTC
Another feature request :

Having the pocket list displayed in its own 'world' felt a bit unusual. Here are some ideas to discuss :

1. have a bulk action for importing
2. how would the plugin know there's already an imported item as a note ?
3. it would be great to have options for selecting what we want to import in a note, like images, tags, highlights and so on.

Just some ideas, maybe other users would find them useful. Again thank you very much for your work.

**Comment by nybbles** [comment] 2021-08-28 00:29
@rezgi, I don't understand the request.. could you clarify some things?
- [ ] What do you mean by a bulk action for importing?
- [ ] "How would the plugin know there's already an imported item as a note?" -> can you describe what you need here? Do you want to be able to associate an already-existing note to a Pocket item, even if its title is different from the Pocket item's title?
- [ ] How do you want images to work? The image URLs are currently being imported and stored, but I'm not sure what makes sense to do with those URLs.

FYI I just added tags in #46 (still need to cut a release for it to be available to users). Highlights is already captured in #34.

**Comment by nybbles** [comment] 2021-08-28 00:29
BTW, this is like.. five different feature requests in one issue 😅 . It would be very helpful in the future if you could file a separate issue for each feature request you have. 🙏

**Comment by rezgi** [comment] 2021-08-30 11:04
@nybbles Hi there. Sorry for not being very clear, in my mind it was one feature. What I imagined was some kind of bulk import + diff of pocket items. Here's an example workflow : 

- I sync my pocket items and display the list (as normal)
- I have the option to "bulk import all pocket items to notes" instead of one by one
- by doing that, the pluging compares the already existing notes in the designated folder (e.g /pocket) and compares the titles in order to import only the ones that don't exist yet.

It's a way to be sure that all my pocket items are synced to obsidian notes in order to avoid duplicates. The limitation is that if the user moves or renames an imported pocket item, it will be imported again. I'm not sure if this feature is needed or useful, I'll leave it open to discussion.

Also just forget about the image/highlight import question, I didn't understand at that time that the plugin imports the pocket item content as is, so my question wasn't relevant.

Thanks a lot !

**Comment by nybbles** [comment] 2021-09-08 00:17
Duplicate of #37

**Closed** 2021-09-08 00:18 UTC
Labels: enhancement, question
