### ISSUE TITLE
Bulk Pocket item note creation 

### ISSUE THREAD

**Issue by Superelmanu** [nybbles/obsidian-pocket#37] opened 2021-08-11 21:58 UTC
Have the possibility to bulk create note from the Pocket sync by CTL+click or check box with.

**Comment by nybbles** [comment] 2021-08-12 01:03
I don't understand what you're describing. Can you describe it more clearly?

**Comment by nybbles** [comment] 2021-08-12 01:03
Also, is this a duplicate of #36?

**Comment by Superelmanu** [comment] 2021-08-12 01:17
Unless I'm doing something wrong here is my understanding of the actual process of creating notes from the pocket plugin in Obsidian:
 calling the plugin selecting one article and repeat the process if you have multiple articles.

It will be time consuming if you want to important 200 Pocket saved articles in Obsidian this way.

I will like to have a check box in the Obsidian plugin to select all the articles that are needed to be created as notes. 
It could work also like in a window explore by control clicking on multiple entry or by shift clicking two entry in the plugin to create all the not that are in between.

**Comment by nybbles** [comment] 2021-08-12 07:03
Are you basically trying to save your entire Pocket list onto Obsidian notes, so that you can clear out your Pocket list, but still have all of the URLs saved in Obsidian?

**Comment by Superelmanu** [comment] 2021-08-12 14:15
Yes, in a way.

**Comment by nybbles** [comment] 2021-08-28 00:45
Okay I understand now. I think that how this would work is not really straightforward, for the following reason: if two Pocket items have the same title (e.g. if you save two different Twitter threads from the same author, the title defaults to the author's name), what should be the right behavior?

**Comment by rezgi** [comment] 2021-08-30 11:07
Oh just noticed this feature request is the same as mine. My issue should be merged with this one.

**Comment by rezgi** [comment] 2021-09-08 12:57
How I see it is a way to know what items have been synced or not, in order to have a clear view of what have been imported and what's new. Maybe mark imported pocket items as 'imported' so that the user knows what has been done or not ?

In this case there would be an action like "sync non-imported items" that would act as bulk import but only for non-imported items. What do you think ?

**Comment by nybbles** [comment] 2021-09-08 16:47
@rezgi and I talked about this over DMs and got to a clear definition of what they are asking for, which is: make it possible to create Obsidian notes for all synced Pocket items that don't already have one. This functionality could be exposed as a command.

Also, the terms we used are:
- syncing -> refers to syncing with the Pocket API
- creating an Obsidian note -> refers to creating an Obsidian note that is associated with a particular Pocket item

We are going to avoid using the term "imported" because it was ambiguous.

@rezgi LMK if there's anything I got wrong or missed.

**Comment by rezgi** [comment] 2021-09-09 11:31
That's exactly it, thanks !

**Comment by nybbles** [comment] 2022-02-14 20:19
Hey I'm revisiting this, because #66 is done and allows for handling of Pocket items with duplicate names, amongst other challenges.

I am thinking about implementing it as follows (make the functionality as simple as possible):
1. A command to create Pocket item notes for all Pocket items that do not yet have notes.
2. A setting to automatically create Pocket item notes when new Pocket items are synced.

Please LMK if you have any feedback/comments/questions about that. I'll try to get going on that shortly.

**Comment by jaded0** [comment] 2022-04-30 22:40
Your suggestion #2 is exactly what I was about to add a feature request for.

**Closed** 2022-05-12 01:07 UTC
Labels: enhancement, Bulk pocket item note creation

**Comment by nybbles** [comment] 2022-05-12 16:40
This is released and available now in 0.8.0. LMK if you have any issues and if this meets your needs.

**Comment by jaded0** [comment] 2022-08-30 20:27
It's perfect!
